/** Premium Addis Ababa seed listings — live Unsplash architecture imagery. */
export const SEED_PROPERTIES = [
  {
    title: 'Skyline Penthouse at Bole Atlas',
    description:
      'Floor-to-ceiling glass, private terrace, and concierge-ready lobby in the heart of Bole Atlas. Ideal for executives seeking premium urban living.',
    price: 185000,
    location: 'Bole Atlas, Addis Ababa',
    listing_type: 'rent',
    category: 'apartment',
    bedrooms: 3,
    bathrooms: 3,
    area: 210,
    status: 'active',
    latitude: 8.9895,
    longitude: 38.7892,
    image_url:
      'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&w=1200&q=80',
    amenities: ['24/7 Security', 'Elevator', 'Backup Generator', 'Furnished', 'Parking'],
    agent_name: 'Hanna Bekele',
    agent_phone: '+251911234567',
    agent_whatsapp: '251911234567',
    is_featured: true,
    views: 124,
  },
  {
    title: 'Kazanchis Executive Apartment',
    description:
      'Renovated high-rise unit steps from ministries and embassies. Open-plan kitchen, dedicated office nook, and city skyline views.',
    price: 12500000,
    location: 'Kazanchis, Addis Ababa',
    listing_type: 'buy',
    category: 'apartment',
    bedrooms: 4,
    bathrooms: 3,
    area: 185,
    status: 'active',
    latitude: 9.0128,
    longitude: 38.7614,
    image_url:
      'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=1200&q=80',
    amenities: ['24/7 Security', 'Elevator', 'Water Tanker', 'Parking', 'Balcony'],
    agent_name: 'Dawit Alemu',
    agent_phone: '+251922345678',
    agent_whatsapp: '251922345678',
    is_featured: true,
    views: 89,
  },
  {
    title: 'CMC Family Villa with Garden',
    description:
      'Spacious villa on a quiet CMC street with mature garden, maid quarters, and double garage. Perfect for diplomatic families.',
    price: 28000000,
    location: 'CMC, Addis Ababa',
    listing_type: 'buy',
    category: 'villa',
    bedrooms: 5,
    bathrooms: 4,
    area: 420,
    status: 'active',
    latitude: 8.9782,
    longitude: 38.8124,
    image_url:
      'https://images.unsplash.com/photo-1613490493576-7fde63acd811?auto=format&fit=crop&w=1200&q=80',
    amenities: ['24/7 Security', 'Garden', 'Backup Generator', 'Water Tanker', 'Parking'],
    agent_name: 'Sara Tadesse',
    agent_phone: '+251933456789',
    agent_whatsapp: '251933456789',
    is_featured: false,
    views: 56,
  },
  {
    title: 'Old Airport Modern Loft',
    description:
      'Industrial-chic loft with double-height ceilings, polished concrete floors, and walkable access to restaurants and gyms.',
    price: 95000,
    location: 'Old Airport, Addis Ababa',
    listing_type: 'rent',
    category: 'apartment',
    bedrooms: 2,
    bathrooms: 2,
    area: 140,
    status: 'active',
    latitude: 8.9831,
    longitude: 38.7821,
    image_url:
      'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=1200&q=80',
    amenities: ['Elevator', 'Internet', 'Furnished', 'Parking'],
    agent_name: 'Michael Girma',
    agent_phone: '+251944567890',
    agent_whatsapp: '251944567890',
    is_featured: false,
    views: 41,
  },
  {
    title: 'Bole Bulbula Riverside Residence',
    description:
      'Bright corner unit overlooking green belts of Bulbula. Master suite with walk-in closet and premium fixtures throughout.',
    price: 145000,
    location: 'Bole Bulbula, Addis Ababa',
    listing_type: 'rent',
    category: 'apartment',
    bedrooms: 3,
    bathrooms: 2,
    area: 175,
    status: 'active',
    latitude: 8.9245,
    longitude: 38.7912,
    image_url:
      'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&w=1200&q=80',
    amenities: ['24/7 Security', 'Water Tanker', 'Elevator', 'Balcony'],
    agent_name: 'Liya Haile',
    agent_phone: '+251955678901',
    agent_whatsapp: '251955678901',
    is_featured: true,
    views: 73,
  },
  {
    title: 'Ayat Hillside Townhouse',
    description:
      'Three-level townhouse in Ayat with panoramic valley views, solar-ready roof, and community playground access.',
    price: 8900000,
    location: 'Ayat, Addis Ababa',
    listing_type: 'buy',
    category: 'house',
    bedrooms: 4,
    bathrooms: 3,
    area: 260,
    status: 'active',
    latitude: 8.9512,
    longitude: 38.8845,
    image_url:
      'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&w=1200&q=80',
    amenities: ['24/7 Security', 'Garden', 'Backup Generator', 'Parking'],
    agent_name: 'Yonas Mekonnen',
    agent_phone: '+251966789012',
    agent_whatsapp: '251966789012',
    is_featured: false,
    views: 38,
  },
  {
    title: 'Lebu Contemporary Starter Home',
    description:
      'Efficient layout for young professionals in Lebu. Low HOA, fiber internet ready, and quick access to the expressway.',
    price: 5200000,
    location: 'Lebu, Addis Ababa',
    listing_type: 'buy',
    category: 'house',
    bedrooms: 3,
    bathrooms: 2,
    area: 155,
    status: 'active',
    latitude: 8.8478,
    longitude: 38.7521,
    image_url:
      'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=80',
    amenities: ['Parking', 'Water Tanker', 'Internet'],
    agent_name: 'Bethel Worku',
    agent_phone: '+251977890123',
    agent_whatsapp: '251977890123',
    is_featured: false,
    views: 29,
  },
  {
    title: 'Sarbet Boutique Flat',
    description:
      'Designer-renovated flat near Sarbet roundabout. Custom cabinetry, smart locks, and whisper-quiet bedrooms.',
    price: 78000,
    location: 'Sarbet, Addis Ababa',
    listing_type: 'rent',
    category: 'apartment',
    bedrooms: 2,
    bathrooms: 1,
    area: 98,
    status: 'active',
    latitude: 9.0012,
    longitude: 38.7389,
    image_url:
      'https://images.unsplash.com/photo-1493809842364-78817add7ffb?auto=format&fit=crop&w=1200&q=80',
    amenities: ['Furnished', 'Internet', '24/7 Security', 'Elevator'],
    agent_name: 'Nahom Desta',
    agent_phone: '+251988901234',
    agent_whatsapp: '251988901234',
    is_featured: false,
    views: 52,
  },
  {
    title: 'Piassa Heritage Loft Conversion',
    description:
      'Character-rich loft in a restored Piassa building. Exposed brick, arched windows, and walking distance to cultural landmarks.',
    price: 6800000,
    location: 'Piassa, Addis Ababa',
    listing_type: 'buy',
    category: 'apartment',
    bedrooms: 2,
    bathrooms: 2,
    area: 120,
    status: 'active',
    latitude: 9.0345,
    longitude: 38.7489,
    image_url:
      'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1200&q=80',
    amenities: ['Backup Generator', 'Water Tanker', 'Internet'],
    agent_name: 'Meron Assefa',
    agent_phone: '+251999012345',
    agent_whatsapp: '251999012345',
    is_featured: true,
    views: 67,
  },
  {
    title: 'Bole Atlas Corporate Suite',
    description:
      'Serviced corporate suite with weekly housekeeping, meeting nook, and underground parking in Bole Atlas business district.',
    price: 220000,
    location: 'Bole Atlas, Addis Ababa',
    listing_type: 'rent',
    category: 'apartment',
    bedrooms: 2,
    bathrooms: 2,
    area: 130,
    status: 'active',
    latitude: 8.9912,
    longitude: 38.7856,
    image_url:
      'https://images.unsplash.com/photo-1600566753190-17f0baa2a6a3?auto=format&fit=crop&w=1200&q=80',
    amenities: ['24/7 Security', 'Elevator', 'Furnished', 'Backup Generator', 'Parking', 'Gym'],
    agent_name: 'AddisNest Concierge',
    agent_phone: '+251900000000',
    agent_whatsapp: '251900000000',
    is_featured: true,
    views: 201,
  },
] as const;

export function buildSeedRows() {
  return SEED_PROPERTIES.map((row) => {
    const imageUrl = row.image_url;
    return {
      ...row,
      images: [imageUrl],
      featured_image: imageUrl,
    };
  });
}
